// Luxury Premium Apartments Collection
export interface LuxuryProperty {
  id: string
  title: string
  arrondissement: number
  price: number
  bedrooms: number
  bathrooms: number
  rating: number
  reviews: number
  image: string
  registrationNumber: string
  dpeRating: 'A' | 'B' | 'C' | 'D' | 'E'
  amenities: string[]
  hasBalcony: boolean
  hasEiffelView: boolean
}

export const luxuryProperties: LuxuryProperty[] = [
  {
    id: 'premium-1',
    title: 'Montparnasse Modern Luxury 2-Bed',
    arrondissement: 14,
    price: 1520,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4.95,
    reviews: 298,
    image: '/apartments/premium-living-1.jpg',
    registrationNumber: '75014PAR2024PREM01',
    dpeRating: 'A',
    amenities: ['AC', 'Elevator', 'Concierge', 'Smart Home'],
    hasBalcony: true,
    hasEiffelView: false,
  },
  {
    id: 'premium-2',
    title: 'Châtelet Penthouse Suite',
    arrondissement: 6,
    price: 1680,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4.98,
    reviews: 342,
    image: '/apartments/premium-living-2.jpg',
    registrationNumber: '75006PAR2024PREM02',
    dpeRating: 'A',
    amenities: ['AC', 'Elevator', 'Concierge', 'Rooftop Terrace'],
    hasBalcony: true,
    hasEiffelView: false,
  },
  {
    id: 'premium-3',
    title: 'Saint-Germain Designer Loft',
    arrondissement: 6,
    price: 2590,
    bedrooms: 1,
    bathrooms: 1,
    rating: 4.92,
    reviews: 267,
    image: '/apartments/premium-studio-1.jpg',
    registrationNumber: '75006PAR2024PREM03',
    dpeRating: 'A',
    amenities: ['AC', 'Elevator', 'Heated Floors', 'Wine Fridge'],
    hasBalcony: true,
    hasEiffelView: false,
  },
  {
    id: 'premium-4',
    title: 'Left Bank Literary Apartment',
    arrondissement: 5,
    price: 750,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4.93,
    reviews: 281,
    image: '/apartments/premium-workspace-1.jpg',
    registrationNumber: '75005PAR2024PREM04',
    dpeRating: 'B',
    amenities: ['Wifi', 'Study Room', 'Library', 'Fireplace'],
    hasBalcony: false,
    hasEiffelView: false,
  },
  {
    id: 'premium-5',
    title: 'Presqu\'île Gourmet Chef\'s Kitchen',
    arrondissement: 7,
    price: 1640,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4.96,
    reviews: 315,
    image: '/apartments/premium-kitchen-1.jpg',
    registrationNumber: '75007PAR2024PREM05',
    dpeRating: 'A',
    amenities: ['AC', 'Professional Kitchen', 'Elevator', 'Wine Cellar'],
    hasBalcony: true,
    hasEiffelView: true,
  },
  {
    id: 'premium-6',
    title: 'Île-de-la-Cité Riverside Elegance',
    arrondissement: 1,
    price: 1350,
    bedrooms: 3,
    bathrooms: 3,
    rating: 4.99,
    reviews: 389,
    image: '/apartments/premium-bedroom-1.jpg',
    registrationNumber: '75001PAR2024PREM06',
    dpeRating: 'A',
    amenities: ['AC', 'Elevator', 'Concierge', 'River View', 'Smart Home'],
    hasBalcony: true,
    hasEiffelView: true,
  },
  {
    id: 'premium-7',
    title: 'Opera District Royal Suite',
    arrondissement: 9,
    price: 1580,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4.91,
    reviews: 276,
    image: '/apartments/premium-bedroom-2.jpg',
    registrationNumber: '75009PAR2024PREM07',
    dpeRating: 'B',
    amenities: ['AC', 'Elevator', 'Marble Bathrooms', 'Crystal Chandeliers'],
    hasBalcony: true,
    hasEiffelView: false,
  },
  {
    id: 'premium-8',
    title: 'Belleville Artist\'s Loft',
    arrondissement: 11,
    price: 1650,
    bedrooms: 2,
    bathrooms: 1,
    rating: 4.88,
    reviews: 243,
    image: '/apartments/premium-hallway-1.jpg',
    registrationNumber: '75011PAR2024PREM08',
    dpeRating: 'B',
    amenities: ['High Ceilings', 'Natural Light', 'Gallery Space', 'Skylights'],
    hasBalcony: true,
    hasEiffelView: false,
  },
  {
    id: 'premium-9',
    title: 'Bastille Spa Sanctuary',
    arrondissement: 12,
    price: 1120,
    bedrooms: 2,
    bathrooms: 3,
    rating: 4.94,
    reviews: 299,
    image: '/apartments/premium-bathroom-1.jpg',
    registrationNumber: '75012PAR2024PREM09',
    dpeRating: 'A',
    amenities: ['AC', 'Steam Shower', 'Spa Bath', 'Elevator'],
    hasBalcony: true,
    hasEiffelView: false,
  },
]
